Fix typo in admin sync mail credentials
The use of `Hash#fetch` in a preceding commit has revealed another case of
using the wrong keys when accessing a hash. When a new user was created it
would raise an exception:

    Sending credentials to new user dan.carley@digital.cabinet-office.gov.uk
    bundler: failed to load command: sync-admin-users.rb (sync-admin-users.rb)
    KeyError: key not found: :source_address
      /tmp/build/fc57e4e1/paas-cf/scripts/lib/mail_credentials_helper.rb:31:in `fetch'
      /tmp/build/fc57e4e1/paas-cf/scripts/lib/mail_credentials_helper.rb:31:in `block in send_email'
      /usr/local/bundle/gems/mail-2.6.4/lib/mail/message.rb:133:in `instance_eval'
      /usr/local/bundle/gems/mail-2.6.4/lib/mail/message.rb:133:in `initialize'
      /usr/local/bundle/gems/mail-2.6.4/lib/mail/mail.rb:51:in `new'
      /usr/local/bundle/gems/mail-2.6.4/lib/mail/mail.rb:51:in `new'
      /tmp/build/fc57e4e1/paas-cf/scripts/lib/mail_credentials_helper.rb:30:in `send_email'
      /tmp/build/fc57e4e1/paas-cf/scripts/lib/mail_credentials_helper.rb:55:in `send_admin_credentials'
      sync-admin-users.rb:56:in `block in <top (required)>'
      sync-admin-users.rb:54:in `each'
      sync-admin-users.rb:54:in `<top (required)>'

When these were previously evaluated to `nil` it didn't affected the
delivery of the message because the envelope details were still correct.