Fix the tag already exist problem
To avoid failures while promoting tag when using cached git resources in
concourse we need to fetch tags before checking if tag already exists.

Also, new test has been created to ensure we don't brake tag promotion
script in the future.

Error message from staging pipeline:

```
To git@github.com:alphagov/paas-cf.git
 ! [rejected]        prod-0.0.101 -> prod-0.0.101 (already exists)
  error: failed to push some refs to
  'git@github.com:alphagov/paas-cf.git'
  hint: Updates were rejected because the tag already exists in the
  remote.
```