Correct initial terraform state file
If "resources" is of type object instead of list, it causes

```
Error: Error loading state: Invalid state file format:
The state file field "resources" has invalid value object
```

when running cf-terrafom/terraform-apply in a new environment.