Fix `discover_external_ip': undefined method `marshal_dump'
The templates expect the entry for networks to be hashmap of the
networks assigned to the job, where the key is the name.

Without setting this network properties some templates might fail with
the following error when they require learn the IP of the host
That is the case of the smoke-tets
(e.g https://github.com/cloudfoundry/cf-release/blob/5fd76c798be025101915912171ab80f85516968f/jobs/smoke-tests/templates/config.json.erb#L3)

(erb):3:in `discover_external_ip': undefined method `marshal_dump' for #<Array:0x007f97fc2d9470> (NoMethodError)
        from (erb):34:in `get_binding'
        from /Users/piotrkomborski/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/erb.rb:863:in `eval'
        from /Users/piotrkomborski/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/erb.rb:863:in `result'
        from /Users/piotrkomborski/go/src/github.com/alphagov/paas-cf/tests/bosh-template-renderer/render_lib.rb:44:in `render_template'
        from ./render.rb:10:in `<main>'